import React from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, ArrowUpRight, BriefcaseBusiness, GraduationCap, MapPinned, Rocket, Users } from 'lucide-react';
import { Kpi, PageHeader, Panel, Shell, Status } from '../../components/ui';
import { impact } from '../../data/demoUniverse';

export function DirectionDashboard() {
    const max = Math.max(...impact.stages.map(stage => stage.value));
    return <Shell role="direction"><div className="role-hero direction-hero"><div><p className="eyebrow">Cockpit Direction · Données de démonstration</p><h1>L’impact de la PNPE,<br /><em>du parcours au territoire.</em></h1><p>Une lecture consolidée pour voir où se crée la valeur, où les parcours ralentissent et où concentrer l’action.</p></div><div className="direction-proof"><img src="/logos/logo.png" alt="" /><div><span>PNPE d’Édéa</span><strong>Observatoire entrepreneurial</strong><small>Actualisé aujourd’hui · 08h30</small></div></div></div>
        <div className="kpi-grid">{impact.kpis.map((item, index) => <Kpi key={item.label} item={item} index={index} />)}</div>
        <div className="direction-grid"><Panel title="Pipeline de transformation" subtitle="De l’orientation à la maturité · cohorte consolidée" action={<Status tone="green">Suivi actif</Status>}><div className="impact-pipeline">{impact.stages.map((stage, index) => <div key={stage.label}><div><span>{stage.label}</span><strong>{stage.value.toLocaleString('fr-FR')}</strong></div><span className="pipeline-track"><motion.i initial={{ width: 0 }} animate={{ width: `${stage.value / max * 100}%` }} transition={{ delay: index * .08, duration: .6 }} /></span><small>{index ? `${Math.round(stage.value / impact.stages[index - 1].value * 100)} % passent l’étape` : '100 % du portefeuille'}</small></div>)}</div></Panel>
            <Panel title="Points de vigilance" subtitle="Signaux nécessitant une décision"><div className="vigilance-list">{impact.vigilance.map(item => <div key={item.label} className={item.tone}><AlertTriangle size={18} /><div><span>{item.label}</span><strong>{item.value}</strong><small>{item.context}</small></div><ArrowUpRight size={16} /></div>)}</div></Panel></div>
        <div className="direction-grid lower"><Panel title="Empreinte territoriale" subtitle="Projets accompagnés et maturité moyenne"><div className="territory-list">{impact.territories.map(item => <div key={item.name}><span><MapPinned size={15} /> {item.name}</span><div><i style={{ width: `${item.projects / 5}px` }} /><strong>{item.projects}</strong><small>{item.maturity}/100</small></div></div>)}</div></Panel><Panel title="Lecture sectorielle" subtitle="Part du portefeuille actif"><div className="sector-wheel"><div className="sector-donut"><strong>34%</strong><span>Agro-industrie</span></div><div className="sector-legend">{impact.sectors.map((item, index) => <div key={item.name}><i className={`sector-${index}`} /><span>{item.name}</span><strong>{item.value}%</strong></div>)}</div></div></Panel></div>
        <div className="institution-strip"><div><Users /><strong>1 248</strong><span>potentiels identifiés</span></div><i /><div><GraduationCap /><strong>92%</strong><span>complétion formation</span></div><i /><div><Rocket /><strong>186</strong><span>projets incubés</span></div><i /><div><BriefcaseBusiness /><strong>74</strong><span>projets financés</span></div></div>
    </Shell>;
}