import React, { useState } from 'react';
import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { toast } from 'sonner';
import {
    ArrowRight, Award, BriefcaseBusiness, Building2, Check, ChevronDown, FileText,
    GraduationCap, Plus, Rocket, Search, Settings2, ShieldCheck, Sparkles, Target, TrendingUp,
} from 'lucide-react';
import { journeyStages, projects } from './data/demoUniverse';
import { formatFcfa, pnpeService } from './services/mockService';
import { Journey, Kpi, Maturity, PageHeader, Panel, Progress, PublicLayout, Shell, Status } from './components/ui';
import { ErrorState, PageSkeleton } from './components/AsyncState';
import { usePnpeResource } from './hooks/usePnpeResource';
import { BeneficiaryDashboard } from './features/beneficiary/BeneficiaryDashboard';
function ProjectCard({ project }) { return <Link to={`/projets/${project.id}`} className="project-card"><div className="project-cover"><span>{project.sector}</span><span className="cover-pattern">{project.name.slice(0, 2).toUpperCase()}</span></div><div className="project-body"><div className="project-title"><h3>{project.name}</h3>{project.verified && <ShieldCheck size={16} />}</div><p>{project.description}</p><div className="project-meta"><span>{project.city}, {project.region}</span><Status tone={project.maturity >= 80 ? 'gold' : 'green'}>{project.status}</Status></div><div className="project-foot"><span><strong>{project.maturity}</strong>/100 maturité</span><span>{formatFcfa(project.amount)}</span></div><Progress value={project.maturity} tone={project.maturity >= 80 ? 'gold' : 'forest'} /></div></Link>; }
function CourseCard({ course }) { return <article className="course-card"><div className={`course-art ${course.color}`}><span>{course.category}</span><GraduationCap size={34} /><strong>{course.price === 0 ? 'GRATUIT' : `${course.price.toLocaleString('fr-FR')} FCFA`}</strong></div><div className="course-body"><Status tone={course.status === 'Recommandée' ? 'blue' : course.status === 'Certifiée' ? 'gold' : 'green'}>{course.status}</Status><h3>{course.title}</h3><p>{course.instructor} · {course.duration} · {course.level}</p><Progress value={course.progress} tone={course.color === 'gold' ? 'gold' : 'forest'} /><div className="course-foot"><span>{course.progress ? `${course.progress}% complété` : `${course.students} apprenants`}</span><button className="text-button" onClick={() => toast.success(course.progress ? 'Reprise de la formation' : 'Formation ajoutée à votre parcours')}>{course.progress ? 'Continuer' : course.price ? 'S’inscrire' : 'Commencer'} <ArrowRight size={14} /></button></div></div></article>; }

function JourneyPage() { return <Shell><PageHeader eyebrow="Mon parcours" title="Chaque étape compte." description="La PNPE relie diagnostic, formation, accompagnement et opportunités dans un même parcours." /><Panel title="Votre feuille de route" subtitle="AgroFresh Cameroun · dernière mise à jour il y a 2 jours"><Journey /><div className="roadmap-list">{journeyStages.map((stage, index) => <div className={`roadmap-row ${index === 4 ? 'current' : ''}`} key={stage.id}><span className="roadmap-check">{index < 4 ? <Check size={14} /> : index === 4 ? <span /> : index + 1}</span><div><strong>{stage.label}</strong><p>{index < 4 ? 'Étape validée dans votre dossier' : index === 4 ? 'Validation marché · en cours' : 'À venir dans votre parcours'}</p></div><Status tone={index < 4 ? 'green' : index === 4 ? 'terracotta' : 'muted'}>{index < 4 ? 'Terminé' : index === 4 ? 'En cours' : 'À venir'}</Status></div>)}</div></Panel></Shell>; }

function CoursesPageContent({ courses: availableCourses }) { const [filter, setFilter] = useState('Toutes'); const visible = filter === 'Toutes' ? availableCourses : availableCourses.filter(c => c.category === filter); return <Shell><PageHeader eyebrow="Centre de formation PNPE" title="Mon apprentissage" description="Découvrez, suivez et valorisez les compétences qui font progresser votre projet." action={<a href="https://campus.studieslearning.com" target="_blank" rel="noreferrer" className="button outline"><Building2 size={16} /> Campus e-learning</a>} /><div className="learning-hero"><div><span className="eyebrow">Votre progression globale</span><h2>4 formations complétées</h2><p>Vos certificats alimentent directement votre Passeport Entrepreneur.</p></div><div className="learning-stat"><strong>68%</strong><Progress value={68} /><span>Score de formation</span></div><Award size={54} /></div><div className="filter-bar"><div className="filters">{['Toutes', 'Entrepreneuriat', 'Finance', 'Commercial', 'Qualité'].map(item => <button key={item} className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><span>{visible.length} formations</span></div><div className="course-grid">{visible.map(course => <CourseCard course={course} key={course.id} />)}</div><Panel title="La chaîne PNPE · Moodle" subtitle="Moodle est votre environnement pédagogique. PNPEKIT organise l'expérience autour de lui."><div className="moodle-chain">{['Catalogue PNPE', 'Inscription', 'Campus Moodle', 'Évaluation', 'Certificat', 'Passeport'].map((item, i) => <div key={item}><span>{i + 1}</span><strong>{item}</strong>{i < 5 && <ArrowRight size={15} />}</div>)}</div></Panel></Shell>; }

function CoursesPage() { const resource = usePnpeResource(pnpeService.getCourses, []); if (resource.status === 'loading') return <Shell><PageSkeleton label="Chargement du catalogue de formations" /></Shell>; if (resource.status === 'error') return <Shell><ErrorState error={resource.error} onRetry={resource.reload} /></Shell>; return <CoursesPageContent courses={resource.data} />; }

function ProjectsPageContent({ projects: availableProjects }) { const [query, setQuery] = useState(''); const [sector, setSector] = useState('Tous les secteurs'); const filtered = availableProjects.filter(p => `${p.name} ${p.owner} ${p.city}`.toLowerCase().includes(query.toLowerCase()) && (sector === 'Tous les secteurs' || p.sector === sector)); return <Shell role="porteur"><PageHeader eyebrow="Banque de projets PNPE" title="Des projets accompagnés, rendus visibles." description="Un portefeuille structuré pour faciliter le sourcing, les partenariats et l'accès aux opportunités." action={<button className="button primary" onClick={() => toast.success('Votre projet est prêt à être partagé')}>Partager mon projet <ArrowRight size={16} /></button>} /><div className="catalogue-intro"><div><Sparkles size={22} /><strong>Un catalogue qui raconte la maturité</strong><p>Chaque projet est présenté avec ses preuves, ses besoins et sa prochaine opportunité.</p></div><div className="catalogue-count"><strong>74</strong><span>projets prêts<br />à découvrir</span></div></div><div className="search-tools"><div className="search-input"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher un projet, un secteur, une ville..." /></div><select value={sector} onChange={e => setSector(e.target.value)}><option>Tous les secteurs</option><option>Agro-industrie</option><option>Packaging</option><option>Énergie</option></select><button className="filter-button"><Settings2 size={17} /> Filtres <span>3</span></button></div><div className="catalogue-meta"><span><strong>{filtered.length}</strong> projets correspondent</span><span>Trié par maturité <ChevronDown size={14} /></span></div><div className="project-grid">{filtered.map(project => <ProjectCard project={project} key={project.id} />)}</div></Shell>; }

function ProjectsPage() { const resource = usePnpeResource(pnpeService.getProjects, []); if (resource.status === 'loading') return <Shell><PageSkeleton label="Chargement de la banque de projets" /></Shell>; if (resource.status === 'error') return <Shell><ErrorState error={resource.error} onRetry={resource.reload} /></Shell>; return <ProjectsPageContent projects={resource.data} />; }

function AdvisorPageContent({ queue }) { return <Shell role="conseiller"><PageHeader eyebrow="Espace conseiller · Aline Mballa" title="Votre file de travail." description="Les personnes qui nécessitent votre intervention, avec le contexte pour agir vite." action={<button className="button primary" onClick={() => toast.success('Nouvelle action créée')}> <Plus size={17} /> Créer une action</button>} /><div className="stats-row"><div><strong>12</strong><span>Dossiers à examiner</span></div><div><strong>8</strong><span>Rendez-vous aujourd'hui</span></div><div className="alert-stat"><strong>5</strong><span>Actions en retard</span></div><div><strong>7</strong><span>Projets prêts à financer</span></div></div><div className="advisor-layout"><Panel title="Interventions prioritaires" subtitle="La prochaine action utile pour chaque porteur" action={<button className="text-button">Filtrer <ChevronDown size={14} /></button>}><div className="advisor-list">{queue.map(item => <div className="advisor-row" key={item.id}><div className="avatar">{item.avatar}</div><div className="advisor-main"><div className="advisor-title"><strong>{item.name}</strong><Status tone={item.blocked ? 'terracotta' : 'green'}>{item.priority}</Status></div><span>{item.project} · maturité {item.maturity}/100</span><p><b>Problème :</b> {item.issue}</p><p><b>Prochaine action :</b> {item.next}</p></div><div className="advisor-side">{item.blocked ? <span className="blocked"><span>{item.blocked}</span> jours bloqué</span> : <span className="today">À faire aujourd'hui</span>}<button className="round-arrow" onClick={() => toast.info(`Dossier de ${item.name} ouvert`)}><ArrowRight size={18} /></button></div></div>)}</div></Panel><Panel title="Vue de portefeuille" subtitle="Répartition de vos porteurs"><div className="portfolio-ring"><div className="donut"><strong>42</strong><span>porteurs</span></div><div className="legend"><span><i className="green" /> En progression <b>24</b></span><span><i className="gold" /> À relancer <b>11</b></span><span><i className="red" /> Bloqués <b>7</b></span></div></div><div className="advisor-tip"><Sparkles size={16} /><span>3 projets sont prêts à franchir une étape cette semaine.</span></div></Panel></div></Shell>; }

function AdvisorPage() { const resource = usePnpeResource(pnpeService.getAdvisorQueue, []); if (resource.status === 'loading') return <Shell><PageSkeleton label="Chargement de la file conseiller" /></Shell>; if (resource.status === 'error') return <Shell><ErrorState error={resource.error} onRetry={resource.reload} /></Shell>; return <AdvisorPageContent queue={resource.data} />; }

function DirectionPageContent({ metrics }) { return <Shell role="direction"><PageHeader eyebrow="Cockpit de pilotage · données de démonstration" title="L'impact de la PNPE, en un regard." description="Une lecture consolidée du parcours : des premiers contacts aux entreprises qui créent de la valeur." action={<div className="header-actions"><button className="button outline" onClick={() => toast.success('Données synchronisées')}><TrendingUp size={16} /> Actualiser</button><button className="button primary" onClick={() => toast.success('Rapport de démonstration généré')}><FileText size={16} /> Exporter le rapport</button></div>} /><div className="kpi-grid">{metrics.kpis.map(item => <Kpi item={item} key={item.label} />)}</div><div className="direction-grid"><Panel title="Le parcours des porteurs" subtitle="Du premier contact aux projets matures"><div className="funnel">{metrics.stages.map(stage => <div className="funnel-row" key={stage.label}><span>{stage.label}</span><div><i style={{ width: `${Math.max(18, stage.value / 1248 * 100)}%` }} /><strong>{stage.value.toLocaleString('fr-FR')}</strong></div></div>)}</div></Panel><Panel title="Répartition sectorielle" subtitle="Part des projets accompagnés"><div className="bars">{metrics.sectors.map((item, i) => <div className="bar-row" key={item.name}><span>{item.name}</span><div><i style={{ width: `${item.value * 2.3}%` }} className={`bar-${i}`} /><b>{item.value}%</b></div></div>)}</div><div className="chart-note"><Target size={16} /> L'agro-industrie représente le premier axe du portefeuille démonstrateur.</div></Panel></div><Panel title="Indicateurs d'impact" subtitle="Ce que les données permettent de piloter"><div className="impact-cards"><div><Rocket size={19} /><strong>186</strong><span>projets en incubation</span></div><div><Building2 size={19} /><strong>74</strong><span>projets matures</span></div><div><BriefcaseBusiness size={19} /><strong>1 460</strong><span>emplois potentiels</span></div><div><Award size={19} /><strong>3 842</strong><span>certificats délivrés</span></div></div></Panel></Shell>; }

function DirectionPage() { const resource = usePnpeResource(pnpeService.getDashboardMetrics, []); if (resource.status === 'loading') return <Shell><PageSkeleton label="Agrégation des indicateurs PNPE" /></Shell>; if (resource.status === 'error') return <Shell><ErrorState error={resource.error} onRetry={resource.reload} /></Shell>; return <DirectionPageContent metrics={resource.data} />; }

function ApplicationPage() { const [sent, setSent] = useState(false); return <PublicLayout><div className="application-page"><div className="application-intro"><span className="eyebrow">Programme Accélération PNPE · Édéa</span><h1>Votre idée mérite<br /><em>un parcours structuré.</em></h1><p>Candidatez au parcours PNPE et bénéficiez d'un diagnostic, de formations, d'un accompagnement et d'opportunités adaptées à votre projet.</p><div className="application-facts"><span><strong>6 mois</strong> de parcours</span><span><strong>4 étapes</strong> d'accompagnement</span><span><strong>100%</strong> suivi en ligne</span></div></div><div className="application-card">{sent ? <div className="success-state"><div className="success-icon"><Check size={30} /></div><span className="eyebrow">Dossier transmis</span><h2>Votre parcours commence ici.</h2><p>Votre candidature de démonstration a été enregistrée. Vous pouvez maintenant suivre chaque étape depuis votre cockpit.</p><Link className="button primary" to="/porteur">Découvrir mon cockpit <ArrowRight size={16} /></Link></div> : <><div className="stepper"><span className="active">1</span><i /><span>2</span><i /><span>3</span></div><span className="eyebrow">Étape 1 sur 3</span><h2>Parlez-nous de votre projet</h2><p className="muted">Ces premières informations nous aideront à vous orienter.</p><label>Nom du projet<input placeholder="Ex. AgroFresh Cameroun" /></label><label>Secteur d'activité<select><option>Agro-industrie</option><option>Numérique</option><option>Artisanat</option><option>Énergie</option></select></label><label>Où en êtes-vous ?<select><option>Une idée à structurer</option><option>Un prototype existe</option><option>Je vends déjà</option></select></label><button className="button primary full" onClick={() => { setSent(true); toast.success('Votre candidature a été enregistrée'); }}>Continuer <ArrowRight size={16} /></button><small>Vous pourrez compléter votre profil et ajouter vos documents à l'étape suivante.</small></>}</div></div></PublicLayout>; }

function ProjectDetail() { const project = projects.find(p => window.location.pathname.endsWith(p.id)) || projects[0]; return <Shell><Link to="/projets" className="back-link">← Retour à la banque de projets</Link><div className="detail-head"><div><Status tone="green">{project.status}</Status><h1>{project.name}</h1><p>{project.description}</p><div className="detail-meta"><span>{project.owner}</span><span>{project.city}, {project.region}</span><span>{project.sector}</span></div></div><Maturity compact /></div><div className="detail-grid"><Panel title="Profil du projet" subtitle="Les informations structurantes partagées par le porteur"><div className="profile-facts"><div><span>Besoin principal</span><strong>{project.need}</strong></div><div><span>Montant recherché</span><strong>{formatFcfa(project.amount)}</strong></div><div><span>Emplois potentiels</span><strong>{project.jobs}</strong></div><div><span>Statut de vérification</span><strong>{project.verified ? 'Projet vérifié' : 'En cours'}</strong></div></div></Panel><Panel title="Preuves du parcours" subtitle="Ce qui rend ce projet lisible pour un partenaire"><div className="proof-list"><span><Check size={15} /> Diagnostic réalisé</span><span><Check size={15} /> 4 formations complétées</span><span><Check size={15} /> 3 certificats associés</span><span><Check size={15} /> Dossier de financement préparé</span></div><button className="button primary full" onClick={() => toast.success('Demande de mise en relation enregistrée')}>Demander une mise en relation <ArrowRight size={16} /></button></Panel></div></Shell>; }

function App() { return <Routes><Route path="/" element={<PublicLayout><div className="landing"><div className="landing-copy"><span className="eyebrow">Pépinière Nationale Pilote d'Entreprises · Edéa</span><h1>De l'idée à<br /><em>l'entreprise.</em></h1><p>Le parcours entrepreneurial numérique de la PNPE : une même plateforme pour orienter, former, accompagner, structurer et faire grandir les projets camerounais.</p><div className="landing-actions"><Link to="/candidater" className="button primary">Commencer mon parcours <ArrowRight size={17} /></Link><Link to="/porteur" className="button ghost">Voir la démonstration <Sparkles size={16} /></Link></div><div className="landing-trust"><span><ShieldCheck size={16} /> Centre de formation</span><span><Rocket size={16} /> Incubateur</span><span><Building2 size={16} /> Pépinière</span></div></div><div className="landing-visual"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-card main"><div className="visual-card-top"><span className="live-dot" /> Parcours PNPE</div><h3>AgroFresh<br /><em>Cameroun</em></h3><div className="visual-score"><div className="mini-ring"><strong>78</strong></div><div><span>Maturité proposée</span><b>Validation marché</b></div></div><Progress value={78} /></div><div className="floating-card cert"><Award size={19} /><div><strong>Certificat obtenu</strong><span>Marketing digital</span></div><Check size={17} /></div><div className="floating-card match"><div className="match-dot">94%</div><div><strong>Opportunité trouvée</strong><span>Correspondance forte</span></div></div></div></div></PublicLayout>} /><Route path="/candidater" element={<ApplicationPage />} /><Route path="/porteur" element={<BeneficiaryDashboard />} /><Route path="/porteur/parcours" element={<JourneyPage />} /><Route path="/porteur/formations" element={<CoursesPage />} /><Route path="/porteur/opportunites" element={<BeneficiaryDashboard />} /><Route path="/porteur/passeport" element={<ProjectDetail />} /><Route path="/projets" element={<ProjectsPage />} /><Route path="/projets/:id" element={<ProjectDetail />} /><Route path="/conseiller" element={<AdvisorPage />} /><Route path="/conseiller/porteurs" element={<AdvisorPage />} /><Route path="/direction" element={<DirectionPage />} /><Route path="/direction/*" element={<DirectionPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }

export default App;