import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Bookmark, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ChevronRight, ClipboardCheck, FileText, Handshake, MoreHorizontal, Plus, Search, Send, Sparkles, Target, Users, X } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeader, Panel, Progress, Shell, Status } from '../../components/ui';
import { partnerApplications, partnerOpportunities, projects } from '../../data/demoUniverse';
import { formatFcfa } from '../../services/mockService';
import { useDemoSession } from '../../stores/DemoSessionStore';

const scoreProject = (project, criteria) => 45 + (criteria.sector === 'Tous' || project.sector === criteria.sector ? 22 : 0) + (criteria.region === 'Toutes' || project.region === criteria.region ? 18 : 0) + (project.maturity >= criteria.maturity ? 15 : 0);

const ToggleGroup = ({ label, values, value, onChange }) => <div className="capsule-group"><strong>{label}</strong><div className="chip-row">{values.map(item => <button type="button" className={`filter-chip ${value === item ? 'selected' : ''}`} key={item} onClick={() => onChange(item)}>{item}</button>)}</div></div>;

export function PartnerProjectsPage() {
    const [filters, setFilters] = useState({ query: '', sector: 'Tous', region: 'Toutes', maturity: '70' });
    const results = useMemo(() => projects.filter(project => `${project.name} ${project.description} ${project.need}`.toLowerCase().includes(filters.query.toLowerCase()) && (filters.sector === 'Tous' || project.sector === filters.sector) && (filters.region === 'Toutes' || project.region === filters.region) && project.maturity >= Number(filters.maturity)), [filters]);
    const set = (key, value) => setFilters(current => ({ ...current, [key]: value }));
    return <Shell role="partenaire"><PageHeader eyebrow="Catalogue qualifié" title="Banque de projets PNPE." description="Explorez tout le portefeuille accompagné. Utilisez les capsules pour affiner, puis ouvrez un dossier pour décider." action={<Link className="button primary" to="/partenaire/matching"><Target size={16} /> Ouvrir le matching</Link>} /><Panel title="Explorer les projets" subtitle={`${results.length} projets visibles · filtres persistants`}><label className="search-input catalogue-search"><Search size={16} /><input value={filters.query} onChange={event => set('query', event.target.value)} placeholder="Rechercher un projet, un besoin ou une ville" /></label><ToggleGroup label="Secteur" values={['Tous', 'Agro-industrie', 'Packaging', 'Énergie']} value={filters.sector} onChange={value => set('sector', value)} /><ToggleGroup label="Territoire" values={['Toutes', 'Littoral', 'Sud']} value={filters.region} onChange={value => set('region', value)} /><ToggleGroup label="Maturité minimale" values={['60', '70', '80']} value={filters.maturity} onChange={value => set('maturity', value)} /></Panel><div className="project-grid refined-project-grid">{results.map(project => <Link to={`/partenaire/projets/${project.id}`} className="project-card" key={project.id}><div className="project-cover"><span>{project.sector}</span><span className="cover-pattern">{project.name.slice(0, 2).toUpperCase()}</span></div><div className="project-body"><div className="project-title"><h3>{project.name}</h3><Status tone={project.verified ? 'green' : 'blue'}>{project.verified ? 'Vérifié' : 'En incubation'}</Status></div><p>{project.description}</p><div className="project-meta"><span>{project.city}, {project.region}</span><span>{project.jobs} emplois</span></div><div className="project-foot"><span><strong>{project.maturity}</strong>/100 maturité</span><span>{formatFcfa(project.amount)}</span></div><Progress value={project.maturity} /></div></Link>)}</div></Shell>;
}

export function PartnerMatchingPage() {
    const [criteria, setCriteria] = useState({ sector: 'Agro-industrie', region: 'Littoral', maturity: 70 });
    const ranked = useMemo(() => projects.map(project => ({ ...project, match: scoreProject(project, criteria) })).sort((a, b) => b.match - a.match), [criteria]);
    return <Shell role="partenaire"><PageHeader eyebrow="Matching déterministe" title="Vos critères deviennent une shortlist expliquée." description="Aucun score opaque : chaque résultat indique les règles qui ont produit sa position." action={<Status tone="blue"><Sparkles size={13} /> Calcul local</Status>} />
        <div className="matching-studio"><aside><h2>Votre mandat</h2><p>Activez des critères. Le classement se met à jour instantanément.</p><ToggleGroup label="Secteur" values={['Tous', 'Agro-industrie', 'Packaging', 'Énergie']} value={criteria.sector} onChange={sector => setCriteria(current => ({ ...current, sector }))} /><ToggleGroup label="Territoire" values={['Toutes', 'Littoral', 'Sud']} value={criteria.region} onChange={region => setCriteria(current => ({ ...current, region }))} /><ToggleGroup label="Maturité minimale" values={[60, 70, 80, 90]} value={criteria.maturity} onChange={maturity => setCriteria(current => ({ ...current, maturity }))} /><button className="text-button" onClick={() => setCriteria({ sector: 'Tous', region: 'Toutes', maturity: 60 })}><X size={14} /> Réinitialiser les critères</button><div className="matching-rule"><Target size={18} /><span>Score proposé : secteur 22 pts, territoire 18 pts, maturité 15 pts.</span></div></aside><section><div className="section-heading"><div><span className="eyebrow">Classement instantané</span><h2>{ranked.length} projets analysés</h2></div><Status tone="blue">3 critères visibles</Status></div>{ranked.map((project, index) => <motion.article layout className="ranked-project" key={project.id}><strong className="rank-number">0{index + 1}</strong><div><Status tone={project.match >= 90 ? 'green' : 'gold'}>{project.match}% de correspondance</Status><h3>{project.name}</h3><p>{project.sector} · {project.city}, {project.region}</p><div className="match-reasons"><span className={criteria.sector === 'Tous' || project.sector === criteria.sector ? 'yes' : ''}><Check size={13} /> Secteur</span><span className={criteria.region === 'Toutes' || project.region === criteria.region ? 'yes' : ''}><Check size={13} /> Territoire</span><span className={project.maturity >= criteria.maturity ? 'yes' : ''}><Check size={13} /> Maturité</span></div></div><Link className="round-arrow" to={`/partenaire/projets/${project.id}`} aria-label={`Voir ${project.name}`}><ArrowRight size={17} /></Link></motion.article>)}</section></div>
    </Shell>;
}

export function PartnerOpportunitiesPage() {
    const [tab, setTab] = useState('Toutes');
    const [selected, setSelected] = useState(partnerOpportunities[0]);
    const [composer, setComposer] = useState(false);
    const visible = partnerOpportunities.filter(item => tab === 'Toutes' || item.status === tab);
    const applications = partnerApplications.filter(item => item.opportunityId === selected?.id);
    return <Shell role="partenaire"><PageHeader eyebrow="Gestion des appels" title="Publiez, qualifiez, décidez." description="Pilotez une opportunité de son brouillon jusqu'à la décision sur les candidatures." action={<button className="button primary" onClick={() => setComposer(true)}><Plus size={16} /> Nouvelle opportunité</button>} />
        <div className="opportunity-kpis"><div><FileText size={19} /><span><strong>3</strong> opportunités</span></div><div><Users size={19} /><span><strong>11</strong> candidatures</span></div><div><ClipboardCheck size={19} /><span><strong>3</strong> à examiner</span></div></div>
        <div className="workspace-tabs" role="tablist">{['Toutes', 'Brouillon', 'Publiée', 'Closes'].map(item => <button role="tab" aria-selected={tab === item} className={tab === item ? 'selected' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>
        <div className="opportunity-workspace"><section className="opportunity-list">{visible.map((item, index) => <motion.button initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} key={item.id} className={`opportunity-list-row ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => setSelected(item)}><span className={`opportunity-type ${item.color}`}><BriefcaseBusiness size={18} /></span><span><Status tone={item.status === 'Publiée' ? 'green' : 'muted'}>{item.status}</Status><strong>{item.title}</strong><small>{item.type} · échéance {item.deadline}</small></span><span className="opportunity-row-count"><strong>{item.applications}</strong><small>candidatures</small></span><ChevronRight size={17} /></motion.button>)}</section><section className="application-workspace"><div className="application-workspace-head"><div><span className="eyebrow">Instruction en cours</span><h2>{selected.title}</h2><p>{selected.budget} · {selected.eligible} projets éligibles</p></div><button className="icon-btn" title="Plus d'actions" aria-label="Plus d'actions"><MoreHorizontal size={19} /></button></div>{applications.length > 0 ? <div className="application-table">{applications.map(item => <article key={item.id}><div><Status tone={item.status === 'Présélectionnée' || item.status === 'Entretien' ? 'green' : 'gold'}>{item.status}</Status><h3>{item.project}</h3><p>{item.owner} · complétude {item.completeness}%</p></div><strong className="application-score">{item.score}%<small>éligibilité</small></strong><div className="application-actions"><button className="icon-btn" title="Ouvrir le dossier" aria-label={`Ouvrir le dossier ${item.project}`} onClick={() => toast.success(`Dossier ${item.project} ouvert`)}><FileText size={16} /></button><button className="button compact outline" onClick={() => toast.success(`${item.project} présélectionné`)}><Check size={14} /> Présélectionner</button></div></article>)}</div> : <div className="board-empty"><FileText /><strong>Aucune candidature</strong><span>Publiez cette opportunité pour ouvrir les candidatures.</span></div>}</section></div>
        {composer && <div className="workspace-overlay" role="presentation" onMouseDown={() => setComposer(false)}><motion.aside className="opportunity-composer" role="dialog" aria-modal="true" aria-labelledby="composer-title" initial={{ x: 40, opacity: 0 }} animate={{ x: 0, opacity: 1 }} onMouseDown={event => event.stopPropagation()}><div className="composer-head"><div><span className="eyebrow">Nouveau brouillon</span><h2 id="composer-title">Publier une opportunité</h2></div><button className="icon-btn" aria-label="Fermer" onClick={() => setComposer(false)}><X size={19} /></button></div><label>Titre de l'opportunité<input defaultValue="Programme d'appui aux unités locales" /></label><ToggleGroup label="Type" values={['Financement', 'Marché', 'Concours']} value="Financement" onChange={() => { }} /><label>Budget ou valeur<input defaultValue="50 M FCFA" /></label><ToggleGroup label="Territoire" values={['Littoral', 'Sud', 'National']} value="Littoral" onChange={() => { }} /><label>Échéance<input type="date" defaultValue="2026-10-30" /></label><div className="composer-actions"><button className="button outline" onClick={() => { setComposer(false); toast.success('Brouillon enregistré'); }}>Enregistrer le brouillon</button><button className="button primary" onClick={() => { setComposer(false); toast.success('Opportunité publiée en démonstration'); }}><Send size={15} /> Publier</button></div></motion.aside></div>}
    </Shell>;
}

export function PartnerConnectionsPage() {
    const { session } = useDemoSession();
    const requested = projects.filter(project => session.connectionRequests.includes(project.id));
    const shortlisted = projects.filter(project => session.partnerShortlist.includes(project.id) && !session.connectionRequests.includes(project.id));
    return <Shell role="partenaire"><PageHeader eyebrow="Relations avec les porteurs" title="Du projet repéré à l’échange qualifié." description="Suivez vos favoris et vos demandes de mise en relation sans perdre le contexte du sourcing." action={<Link className="button primary" to="/partenaire/projets"><Search size={16} /> Trouver des projets</Link>} />
        <div className="relationship-summary"><div><strong>{shortlisted.length}</strong><span>en shortlist</span></div><div><strong>{requested.length}</strong><span>demandes envoyées</span></div><div><strong>1</strong><span>rendez-vous confirmé</span></div><div><strong>1</strong><span>relation active</span></div></div><div className="relationship-list"><div className="relationship-head"><span>Projet</span><span>Étape actuelle</span><span>Dernier événement</span><span>Prochaine action</span><span /></div>{shortlisted.map(project => <ConnectionCard key={project.id} project={project} state="shortlist" />)}{requested.map(project => <ConnectionCard key={project.id} project={project} state="sent" />)}<ConnectionCard project={projects[1]} state="active" />{shortlisted.length === 0 && requested.length === 0 && <EmptyConnection text="Ajoutez des projets depuis la banque pour alimenter votre pipeline." />}</div>
    </Shell>;
}

function ConnectionCard({ project, state }) { const label = state === 'active' ? 'Rendez-vous confirmé' : state === 'sent' ? 'Qualification PNPE' : 'Shortlist'; return <article className={`relationship-row ${state}`}><div className="relationship-project"><span className="connection-logo">{state === 'active' ? <Handshake /> : <BriefcaseBusiness />}</span><span><strong>{project.name}</strong><small>{project.owner} · {project.sector}</small></span></div><Status tone={state === 'active' ? 'green' : state === 'sent' ? 'blue' : 'gold'}>{label}</Status><span><strong>{state === 'active' ? 'Rendez-vous confirmé' : state === 'sent' ? 'Dossier transmis à la PNPE' : 'Projet ajouté au mandat'}</strong><small>{state === 'active' ? 'Aujourd’hui · 09h12' : 'Hier · 16h40'}</small></span><span><strong>{state === 'active' ? 'Préparer l’échange' : state === 'sent' ? 'Attendre la validation PNPE' : 'Demander la mise en relation'}</strong><small>{formatFcfa(project.amount)} · maturité {project.maturity}/100</small></span><Link className="round-arrow" to={`/partenaire/projets/${project.id}`} aria-label={`Ouvrir ${project.name}`}><ArrowRight size={16} /></Link></article>; }
function EmptyConnection({ text }) { return <div className="board-empty"><Handshake /><strong>Aucun élément</strong><span>{text}</span></div>; }

export function PartnerProjectActions({ project }) {
    const { session, requestConnection, togglePartnerShortlist } = useDemoSession();
    const saved = session.partnerShortlist.includes(project.id); const sent = session.connectionRequests.includes(project.id);
    return <div className="partner-detail-actions"><button className={`button ${saved ? 'success' : 'outline'}`} onClick={() => { togglePartnerShortlist(project.id); toast.success(saved ? 'Projet retiré de la shortlist' : 'Projet ajouté à la shortlist'); }}><Bookmark size={16} fill={saved ? 'currentColor' : 'none'} /> {saved ? 'Dans la shortlist' : 'Ajouter à la shortlist'}</button><button className="button primary" disabled={sent} onClick={() => { requestConnection(project.id); toast.success('Demande transmise à la PNPE'); }}>{sent ? <CheckCircle2 size={16} /> : <Send size={16} />}{sent ? 'Demande envoyée' : 'Demander une mise en relation'}</button></div>;
}